# Generated by Django 4.1 on 2022-09-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0002_alter_size_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="size",
            name="title",
            field=models.CharField(
                choices=[("1", "Small"), ("2", "Medium"), ("3", "Large")],
                max_length=10,
                verbose_name="Size",
            ),
        ),
    ]
